language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_install:
  - npm install --ignore-scripts
  - npm install --save-dev babel-plugin-transform-runtime
  - npm install --save-dev babel-preset-stage-2
  - npm run build
script:

